# Generated by Django 5.1.3 on 2024-11-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='packages_short_paragraph',
            field=models.TextField(null=True),
        ),
    ]
