# Generated by Django 5.1.3 on 2024-11-14 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_packages_packages_short_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='country_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None),
        ),
        migrations.AddField(
            model_name='packages',
            name='itinerary',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='packages',
            name='packages_sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='packages_images/'),
        ),
        migrations.AddField(
            model_name='packages',
            name='packages_sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='packages_images/'),
        ),
    ]
