# Generated by Django 5.1.3 on 2024-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_packages_country_name_packages_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packages_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packages_sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packages_sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
