# Generated by Django 5.1.3 on 2024-11-15 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_packages_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
