# Generated by Django 5.1.3 on 2024-11-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_alter_packages_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
