# Generated by Django 5.1.3 on 2024-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_remove_packages_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='features',
            field=models.TextField(null=True),
        ),
    ]
