# Generated by Django 5.1.3 on 2024-11-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_remove_packages_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
