# Generated by Django 5.1.3 on 2024-11-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0012_delete_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('package_title', models.CharField(max_length=100)),
                ('package_shot_description', models.CharField(max_length=100)),
            ],
        ),
    ]
