# Generated by Django 5.1.3 on 2024-11-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_rename_package_image_packages_packages_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='packages_image',
            new_name='packages_images',
        ),
    ]
