# Generated by Django 5.1.3 on 2024-11-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_rename_packages_image_packages_packages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='packages_shot_description',
            field=models.TextField(null=True),
        ),
    ]
