# Generated by Django 5.1.3 on 2024-11-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_packages_packages_shot_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='packages_images',
        ),
    ]
