# Generated by Django 5.1.3 on 2024-11-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_remove_packages_packages_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
