# Generated by Django 5.1.3 on 2024-11-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0020_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='package_name',
            new_name='title',
        ),
    ]
