# Generated by Django 5.1.3 on 2024-11-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0022_rename_title_packages_packagetitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
