# Generated by Django 5.1.3 on 2024-11-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0024_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_all_packages',
            name='country',
            field=models.CharField(default='Unknown Country', max_length=100),
        ),
        migrations.AddField(
            model_name='view_all_packages',
            name='details_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='view_all_packages',
            name='duration',
            field=models.CharField(default='Unknown Date', max_length=100),
        ),
        migrations.AddField(
            model_name='view_all_packages',
            name='image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='packages_images/'),
        ),
        migrations.AddField(
            model_name='view_all_packages',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='view_all_packages',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='packages_images/'),
        ),
        migrations.AddField(
            model_name='view_all_packages',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='packages_images/'),
        ),
    ]
