# Generated by Django 5.1.3 on 2024-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0025_view_all_packages_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_all_packages',
            name='features',
            field=models.JSONField(default=list, help_text='Enter features as a list.'),
        ),
    ]
